//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carro.compas.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ventas
    {
        public int id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<int> venta_id { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
