//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carro.compas.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Conexiones : DbContext
    {
        public Conexiones()
            : base("name=Conexiones")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<cliente_tipo> cliente_tipo { get; set; }
        public virtual DbSet<detalle_ventas> detalle_ventas { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<opinion> opinions { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<sub_categorias> sub_categorias { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
