//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carro.compas.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opinion
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo_opinion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cliente_tipo_id { get; set; }
        public Nullable<int> producto_id { get; set; }
    
        public virtual cliente_tipo cliente_tipo { get; set; }
        public virtual producto producto { get; set; }
    }
}
